### ISSUE TITLE
Decode HTML entities

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/gwf-publications#12]
E.g., https://gwf-uwaterloo.github.io/gwf-publications/G22-4001/

Take `p&lt;0.001` and decode back to `p<0.001`

**Comment by lintool** [comment]
This happens in titles, also, e.g., https://gwf-uwaterloo.github.io/gwf-publications/G22-9003/

**Comment by lintool** [comment]
As well as character entities, e.g., https://gwf-uwaterloo.github.io/gwf-publications/G22-11001/

```
...recommendations ranges from 62-81&#x0025; and has achieved 8-45&#x0025; ...
```

**Comment by mobehbooei** [comment]
Done

**Comment by lintool** [comment]
Awesome!

**Comment by lintool** [comment]
Hey @mobehbooei - issue still here for this paper: https://gwf-uwaterloo.github.io/gwf-publications/G21-71002/

**Comment by lintool** [comment]
Also: https://gwf-uwaterloo.github.io/gwf-publications/G20-18001/

I think `<sup>` and `<sub>` can be translated into superscripts and subscripts in HTML?
Interesting, the translation is current in the citation:

<img width="826" alt="Screen Shot 2022-12-08 at 8 05 54 AM" src="https://user-images.githubusercontent.com/313837/206454087-0afb0ead-2cf4-47ad-8fac-311a5c380a6c.png">

**Comment by lintool** [comment]
Another one: https://gwf-uwaterloo.github.io/gwf-publications/G22-99001/
